### ISSUE TITLE
Use source-map devtool for Webpack

### ISSUE THREAD

**Issue by ghost** [DimitriMikadze/express-react-redux-starter#2]
This kit is good for getting started; I really appreciate the minimalism. Thanks for putting it together.

In my experience `cheap-eval-source-map` has never rendered source maps correctly, and I'm seeing the same behavior with this starter kit in Chrome 51. After updating the Webpack `devool` to `source-map` and restarting dev, source maps function as expected. And they're super helpful. Might be a good addition to the kit.

**Comment by DimiMikadze** [comment]
Thank you!

I'm using devtool: 'source-map' for webpack production configuration and cheap-eval-source-map for development configuration. so you are suggesting to switch devtool to source-map also for development environment ?

**Comment by ghost** [comment]
For better step debugging in the browser, yes. I usually keep source maps off in prod to help obscure intellectual property and safeguard code.

**Comment by DimiMikadze** [comment]
yes, makes sense, thanks!
