### ISSUE TITLE
Add Object Spread from ES7

### ISSUE THREAD

**Issue by ghost** [DimitriMikadze/express-react-redux-starter#3]
While working with Redux I've found it tremendously helpful to use the spread operator `...` in my reducers as suggested by Dan Abramov in [Getting Started with Redux](https://egghead.io/courses/getting-started-with-redux). Adding it allows one to do the following:

``` js
return {
  ...state,
  currentTime: action.time,
}
```

Instead of:

``` js
return Object.assign({}, state, {
  currentTime: action.time,
});
```

`Object.assign` is called under the hood.

If you'd like to add to this kit just `npm i -D transform-object-rest-spread eslint-plugin-prefer-object-spread` and update the Babel config as such:

```
{
  "presets": ["react", "es2015", "stage-1"],
  "plugins": [
    "transform-object-rest-spread"
  ]
}
```

And change your ESLint config file to:

``` json
{
  "extends": "airbnb",
  "parserOptions": {
    "ecmaVersion": 6,
    "ecmaFeatures": {
      "experimentalObjectRestSpread": true
    }
  },
  "plugins": [
    "prefer-object-spread"
  ],
  "rules": {
    "prefer-object-spread/prefer-object-spread": "error"
  },
}
```

The ESLint plug-in and rule are optional.

**Comment by DimiMikadze** [comment]
Hey,

Agreed! spread operator ... is really helpful.

Do you have problems to use spread operator with this starter kit ? I think, you don't need to add any additional package to use it, because i'm already using them with this starter kit.

**Comment by ghost** [comment]
I started using this kit yesterday for a quick prototype and the lint plug-in for Atom editor (I recently switched after several years of SublimeText) errored on using it in a reducer. With that the ESLint update is recommended. I'll see if I can remove the Babel plug-in and check if it still works in my reducers (and not just in JSX).
