### ISSUE TITLE
Heroku deployment tweaks

### ISSUE THREAD

**Issue by gazpachu** [DimitriMikadze/express-react-redux-starter#7]
- [ ] It's missing the PM2 dependency for production in `package.json`. Add `"pm2": "^2.1.6"`
- [ ] Add the hook: "postinstall": "rm -rf dist && webpack --config ./webpack/webpack-prod.config.js --colors"
- [ ] Move most of the dev-dependencies to dependencies, as Heroku will need them to build the app

**Comment by DimiMikadze** [comment]
Hey gazpachu,

I  have a note written in Readme file regarding PM2.

"Note: I'm using pm2 for production server, you should install it on server via 'npm install pm2 -g'. if you don't want to use pm2, just change pm2 with node in package.json file, in scripts section."

I have never used Heroku, i always use Digital ocean, so i don't know, how things work over there :)

**Comment by gazpachu** [comment]
@DimitriMikadze thanks for the note about the readme file. I forgot about it! :)

Let's close the issue, as this is something related with the production platform. At least, we can have it here, in case anybody is looking for help regarding heroku.

**Comment by DimiMikadze** [comment]
Yes, Thanks! :)
