### ISSUE TITLE
npm run start pm2: not found

### ISSUE THREAD

**Issue by harryandriyan** [DimitriMikadze/express-react-redux-starter#8]
Hello,

I just try this starter kit, when I run npm run start i got this error `sh: 1: pm2: not found`
any ide ?

Thanks before

**Comment by DimiMikadze** [comment]
Hey,

"Note: I'm using pm2 for production server, you should install it on server via 'npm install pm2 -g'. if you don't want to use pm2, just change pm2 with node in package.json file in scripts section."

For development use npm run dev

**Comment by harryandriyan** [comment]
thanks @DimitriMikadze (y)
